### PR TITLE
Converted Model initialization from promise to model object

### PR DESCRIPTION
**Pull request by pratyushmittal**
Model initialization does not perform any input/output or network process. Using multiple models was a pain as we needed to nest initializations into callbacks (if not using ES7) and it often created race conditions.

This pull request converts the model initialization from promise to a model object. I have updated the README to reflect the new usage. I have also added a `breaking-changes.md` to document the change.

Do let me know if any modifications are needed.

### CODE REVIEW

**Comment by pratyushmittal** [comment]
I haven't been able to test the commits on actual device and have relied on Jest tests. Please ensure these work well on actual device before merging :stuck_out_tongue_winking_eye: .

**Comment by thewei** [comment]
thank you very much. 
My english is poor. Thank you for wrote documentation for this lib.
It is a good job.

**Comment by pratyushmittal** [comment]
Thanks @thewei for quick merges and near instant responses.

Though your English looks quite fine, do let me know if you need any help in documentation.

Xiè Xie.

**Comment by thewei** [comment]
ok

**Pull request merged**
