### PR TITLE
Fix - slice results if limit and offset are defined

### PR DESCRIPTION
**Pull request by vermilion1**

### CODE REVIEW

**Comment by thewei** [comment]
@vermilion1 because you what to change the api , I can't merge pull request，so I want to know why you what to change the api

you can use api like this: 

```
 articles. limit(10).find();
```

**Comment by vermilion1** [comment]
@thewei This API doesn't work properly [because of this line](https://github.com/thewei/react-native-store/blob/master/index.js#L287). My commit fixes it and also fixes `get` method - [it supposed to return only one found element](https://github.com/thewei/react-native-store/blob/master/index.js#L251).
I agree that `find` method shouldn't take any arguments and will make a change to it in one-two days.

**Comment by vermilion1** [comment]
@thewei Fixed, now we limit `get` method to 1 result, and `find` method takes into account `_limit` property. No API changes :)

**Comment by thewei** [comment]
Thank you

**Pull request merged**
